# Change these first
owner: oatnog # Your GitHub organization or username, where this repository lives
repo: UHH-PacIOOS-monitoring # The name of this repository

sites:
  - name: hppk SORT
    url: http://sunrise.soest.hawaii.edu/data/hppk/latest_hppk.SORT_ant.gif
  - name: hppk RAD
    url: http://sunrise.soest.hawaii.edu/data/hppk/latest_hppk.RAD_DirF_anim.gif
  - name: hkkh SORT
    url: http://sunrise.soest.hawaii.edu/data/hkkh/latest_hkkh.SORT_ant.gif
  - name: hkkh RAD
    url: http://sunrise.soest.hawaii.edu/data/hkkh/latest_hkkh.RAD_Beam_anim.gif

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /UHH-PacIOOS-monitoring
  logoUrl: https://raw.githubusercontent.com/UHH-PacIOOS-monitoring/assets/pacioos-logo.png
  name: PacIOOS Website Status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Are my buoys sending their data?
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
